CREATE DATABASE GERENCIADOR_TAREFAS CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI; 
USE GERENCIADOR_TAREFAS;

CREATE TABLE ESTADO (
    CODIGO_ESTADO INT PRIMARY KEY AUTO_INCREMENT,
    DESCRICAO_ESTADO VARCHAR (50)
) ENGINE = INNODB;

CREATE TABLE TAREFA (
    CODIGO_TAREFA INT PRIMARY KEY AUTO_INCREMENT,
    CODIGO_ESTADO INT DEFAULT 1,
    DESCRICAO_TAREFA VARCHAR (250),
    DATA_CADASTRO DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (CODIGO_ESTADO) REFERENCES ESTADO(CODIGO_ESTADO)
) ENGINE =  INNODB;

INSERT INTO ESTADO(DESCRICAO_ESTADO) VALUES ('iniciada'), ('pausada'), ('pendente'), ('processada'), ('finalizada');
INSERT INTO TAREFA (DESCRICAO_TAREFA) VALUES ('Fazer tarefa de login');

SELECT * FROM TAREFA;
UPDATE TAREFA SET DESCRICAO_TAREFA = "FAZER TELA DE LOGIN" WHERE CODIGO_TAREFA = 2;

DELETE FROM TAREFA WHERE CODIGO_TAREFA = 1;